//! i18n bootstrap. Wraps gettext-rs and exposes the `t!()` macro used at every
//! user-facing call site.

use anyhow::{Context, Result};
use gettextrs::{
    bind_textdomain_codeset, bindtextdomain, gettext, setlocale, textdomain, LocaleCategory,
};

const DOMAIN: &str = "clipsneko-installer";

/// Supported installer UI languages. The variant order is the order shown in
/// the language picker.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)] // ZhCn wired up when the language picker step (§4.1) lands.
pub enum UiLang {
    En,
    ZhCn,
}

impl UiLang {
    /// POSIX locale code used for `setlocale` and `bindtextdomain` lookups.
    pub fn code(self) -> &'static str {
        match self {
            UiLang::En => "en_US.UTF-8",
            UiLang::ZhCn => "zh_CN.UTF-8",
        }
    }

    /// Human-readable label shown in the picker itself (kept in English so the
    /// picker is usable before any translation is active).
    #[allow(dead_code)] // Used by the language picker step (§4.1).
    pub fn label(self) -> &'static str {
        match self {
            UiLang::En => "English",
            UiLang::ZhCn => "简体中文 (Simplified Chinese)",
        }
    }
}

/// Initialize gettext with the given UI language. Must be called once at
/// startup; calling it again switches the active translation at runtime.
pub fn set_language(lang: UiLang) -> Result<()> {
    // setlocale must succeed for gettext to pick the right .mo file. On the
    // Live ISO the required UTF-8 locales are generated by default; if they
    // are missing the user gets a clear error instead of silent fallback.
    setlocale(LocaleCategory::LcAll, lang.code()).with_context(|| {
        format!(
            "setlocale({}) failed; locale not generated on this system",
            lang.code()
        )
    })?;

    let locale_dir = std::env::var("CLIPSNEKO_LOCALEDIR")
        .unwrap_or_else(|_| env!("CLIPSNEKO_DEV_LOCALEDIR").to_string());
    bindtextdomain(DOMAIN, &locale_dir)
        .with_context(|| format!("bindtextdomain({}, {}) failed", DOMAIN, locale_dir))?;
    bind_textdomain_codeset(DOMAIN, "UTF-8").context("bind_textdomain_codeset failed")?;
    textdomain(DOMAIN).context("textdomain failed")?;
    Ok(())
}

/// Translate a string via the active gettext catalog.
pub fn translate(s: &str) -> String {
    gettext(s)
}

/// Translate a literal at the call site. Usage: `t!("Welcome")`. The input
/// must be a `&'static str` so xgettext can extract it from source.
#[macro_export]
macro_rules! t {
    ($s:expr) => {
        $crate::i18n::translate($s)
    };
}
