name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      
      - name: Install gettext
        run: |
          sudo apt update
          sudo apt install -y gettext

      - name: Build
        run: cargo build --release
